version: "3.7"
services:

  solr:
    image: governors-election-solr
    build: ./solr
    ports:
      - "8983:8983"
    volumes:
      - "governors-election-data:/opt/solr/server/solr/mycores/governors-election"

  logstash:
    image: governors-election-logstash
    build: ./logstash

  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

volumes:
   governors-election-data:

