version: "3.7"
services:

  corrd:
    image: governors-election-solr
    build: .
    ports:
      - "8983:8983"
    volumes:
      - "governors-election-data:/opt/solr/server/solr/mycores/governors-election"

volumes:
   governors-election-data:

